#Get all the books
GET  http://127.0.0.1:3001/books HTTP/1.1
Content-Type: application/json

###

#create a book
POST http://127.0.0.1:3001/books HTTP/1.1
Content-Type: application/json

	{
		"title": "The lord of the ring"
    }

###
#update book
PUT http://127.0.0.1:3001/books/4 HTTP/1.1
Content-Type: application/json

{
	"title" : "la terre et le sang"
}
###
#delete a book
DELETE http://127.0.0.1:3001/books/4 HTTP/1.1
Content-Type: application/json 